DEFAULT_NICKNAME = "{DiscordJockey}"
DATABASE_FILE_LOCATION = "./database/diary_data.db"
LOG_FILE_LOCATION = "./diary_bot/diary_bot.log"

STARTUP_MESSAGE = "Starting Bot..."
STARTUP_COMPLETE_MESSAGE = "Startup Complete"

BOT_CONFIG_ERROR_MESSAGE = "Error: An error occurs during the bot is configuration"
BOT_RUNNING_ERROR_MESSAGE = "Error: An error occurs while the bot is running"
CONNECT_DATABASE_AND_TABLE = "It was connect to diary_database and contents tables."
DIARY_IMAGE_RETRIEVAL_ERROR_MESSAGE = "Error: An error occurs when retrieving the image of the diary"
DIARY_REGISTRATION_ERROR_MESSAGE = "Error: An error occurs when registering the diary in the database"
DIARY_DELETE_ERROR_MESSAGE = "Error: An error occurs when deleting the diary from the database"
SHOW_CONTENTS_ERROR_MESSAGE = "Error: An error occurs when displaying all contents of the registered diary"
FIND_MESSAGE_FROM_LETTERS_ERROR_MESSAGE = "Error: An error occurs when searching for a diary that contains the entered characters in find_message_from_letters()"
FIND_MESSAGE_FROM_WORD_ERROR_MESSAGE = "Error: An error occurs when searching for a diary that contains the entered word in find_message_from_word()"
FIND_MESSAGE_FROM_DATE_ERROR_MESSAGE = "Error: An error occurs when searching for a diary registered on the entered date in find_message_from_date()"
FIND_MESSAGE_FROM_TIME_ERROR_MESSAGE = "Error: An error occurs when searching for a diary registered within the entered time in find_message_from_time()"

HELP_NEKO_SHORT = "Responds with 'にゃーん'"
HELP_NEKO_LONG = "The bot responds with 'にゃーん' when the '/neko' command is used."
HELP_ADD_SHORT = "Add diary content to the database"
HELP_ADD_LONG = "The '/add' command will add diary entries to the database. The entries must follow the command like this: '/add XXXX'."
HELP_DELRC_SHORT = "Delete the most recent diary content from the database"
HELP_DELRC_LONG = "The '/delrc' command will delete the most recent diary entry from the database. Use the command like this: '/delrc'."
HELP_SHOW_ALL_SHORT = "Show all diary entries"
HELP_SHOW_ALL_LONG = "The '/showme_all_contents' command will display all diary entries in the database."
HELP_FL_SHORT = "Find diary entries containing the input string"
HELP_FL_LONG = "The '/fl' command will find and display diary entries that contain the input string. The string must follow the command like this: '/fl XXXX'."
HELP_FW_SHORT = "Find diary entries containing the input word"
HELP_FW_LONG = "The '/fw' command will find and display diary entries that contain the input word. The word must follow the command like this: '/fw XXXX'."
HELP_FD_SHORT = "Find diary entries from the input date"
HELP_FD_LONG = "The '/fd' command will find and display diary entries from the input date. The date must follow the command like this: '/fd YYYY-MM-DD'."
HELP_FT_SHORT = "Find diary entries within the input time range"
HELP_FT_LONG = "The '/ft' command will find and display diary entries within the input time range. The time range must follow the command like this: '/ft HH:MM-HH:MM'."
